[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "flask-caching>=2.3.1",
    "flask>=3.1.0",
    "flask-assets>=2.1.0",
]
